### ISSUE TITLE
Sort or filter by "Is not on a list"

### ISSUE THREAD

**Issue by thomasmdickinson** [afk-mario/federike#28]
### Pitch

I'd like to be able to sort or filter the left hand "Following" column by whether or not someone is already in one or more lists.

### Motivation

Personally, I'd like to have everyone in a list, so making it easier to spot people who are not yet in one or more lists would be super helpful. The little list tags are great for this, but a sort or filter option would be even better.

**Comment by afk-mario** [comment]
This is something that I want as well! just the structure of the data makes it a little hard to do right so will probably take some time

**Comment by afk-mario** [comment]
Just pushed a new version `0.1.6` with the ability to sort by lists, filtering will be done on #7
